clickhouse:
  addr: "<CLICKHOUSE_SECURE_NATIVE_HOSTNAME>:9440"
  database: "default"
  username: "default"
  password: "<DEFAULT_USER_PASSWORD>"

app:
  query: select count(*) from pf_results where created_at between toString(date_add(hour ,-1,now())) and toString(now())